name: pyzstd

# Build on every branch push, tag push, and pull request change.
on: [push, pull_request]

env:
  PYTHON_VER: '3.10'        # Python to run test/cibuildwheel
  PYTHON_VER_PEP489: '3.11' # Python to run test with multi-phase init
  CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-* cp311-* pp37-* pp38-* pp39-*
  CIBW_TEST_COMMAND: python {project}/tests/test_zstd.py

jobs:
  # Run test on Ubuntu/macOS/Windows for every commit
  run_test:
    name: Test on ${{ matrix.platform }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        architecture: [x64]
        include:
          - platform: windows-latest
            architecture: x86

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VER }}
          architecture: ${{ matrix.architecture }}

      - name: Run test
        run: |
          python -m pip install --config-settings="--build-option=--warning-as-error" -vv .
          python -c "import pyzstd; print('PYZSTD_CONFIG:', pyzstd.PYZSTD_CONFIG)"
          python tests/test_zstd.py

  # Run test with multi-phase init on Ubuntu/macOS/Windows
  run_test_with_multi_phase_init:
    name: Test on ${{ matrix.platform }} ${{ matrix.architecture }} with multi-phase init
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        architecture: [x64]
        include:
          - platform: windows-latest
            architecture: x86

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VER_PEP489 }}
          architecture: ${{ matrix.architecture }}

      - name: Run test with multi-phase init
        run: |
          python -m pip install --config-settings="--build-option=--warning-as-error --multi-phase-init" -vv .
          python -c "import pyzstd; print('PYZSTD_CONFIG:', pyzstd.PYZSTD_CONFIG)"
          python tests/test_zstd.py

  # Run test on PyPy for every commit
  test_on_pypy:
    name: Test on ${{ matrix.py }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        py: ['pypy-3.7', 'pypy-3.8', 'pypy-3.9']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Build & test
        run: |
          sudo apt-get install -q -y zstd libzstd1 libzstd-dev
          python -m pip install --config-settings="--build-option=--dynamic-link-zstd" -v .
          python -c "import pyzstd; print('PYZSTD_CONFIG:', pyzstd.PYZSTD_CONFIG)"
          python tests/test_zstd.py

  # Build Linux/macOS/Windows wheels
  build_wheels:
    name: Build wheels on ${{ matrix.platform }}
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/heads/release')
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    env:
      # macOS archs
      CIBW_ARCHS_MACOS: "x86_64 arm64"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VER }}

      # cibuildwheel and PEP-517 don't work on CPython 3.6. This can
      # be removed after cibuildwheel doesn't support CPython 3.6.
      - name: Remove pyproject.toml
        uses: JesseTG/rm@v1.0.3
        with:
          path: pyproject.toml

      - name: Install cibuildwheel & build wheels
        run: |
          python -m pip install -U cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: pyzstd-files
          path: wheelhouse/*.whl

  # Build source distribution & manylinux1_x86_64 wheels
  # These two jobs build:
  #   1, build_wheels (above): manylinux1_i686 / manylinux2014_x86_64
  #   2, build_in_manylinux2010 (this): manylinux1_x86_64
  # manylinux2014_x86_64 wheels use a new memcpy() function
  # (memcpy@GLIBC_2.14), so the wheels are not compatible with
  # manylinux1_x86_64 environment. In order to be compatible as
  # much as possible, this job builds manylinux1_x86_64 wheels.
  build_in_manylinux2010:
    name: Build in manylinux2010 environment
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/heads/release')
    runs-on: ubuntu-latest

    env:
      # Generate manylinux1_x86_64 wheels.
      #     tag         pip      CPython with the pip      glibc
      # manylinux1     >=8.1.0  3.5.2+, 3.6.0+            2.5  (2006-09-29)
      # manylinux2010  >=19.0   3.7.3+, 3.8.0+            2.12 (2010-05-03)
      # manylinux2014  >=19.3   3.7.8+, 3.8.4+, 3.9.0+    2.17 (2012-12-25)
      # manylinux_x_y  >=20.3   3.8.10+, 3.9.5+, 3.10.0+  x.y
      # manylinux2010 images EOL on 2022-08-01, it doesn't support cp311/pp39.
      CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-* pp37-* pp38-*
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2010
      CIBW_MANYLINUX_PYPY_X86_64_IMAGE: manylinux2010
      CIBW_ARCHS_LINUX: x86_64
      CIBW_SKIP: "*musllinux*"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VER }}

      # cibuildwheel and PEP-517 don't work on CPython 3.6. This can
      # be removed after cibuildwheel doesn't support CPython 3.6.
      - name: Remove pyproject.toml
        uses: JesseTG/rm@v1.0.3
        with:
          path: pyproject.toml

      - name: Build source distribution & wheels
        run: |
          python -m pip install -U build cibuildwheel
          python -m build --sdist
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload source distribution
        uses: actions/upload-artifact@v3
        with:
          name: pyzstd-files
          path: dist/*.tar.gz

      - name: Upload manylinux1_x86_64
        uses: actions/upload-artifact@v3
        with:
          name: pyzstd-files
          path: wheelhouse/*.whl

  # Build aarch64/ppc64le/s390x wheels
  build_arch_wheels:
    name: Build ${{ matrix.arch }} wheels
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/heads/release')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [aarch64, ppc64le, s390x]
        # Building in QEMU is very slow, so parallelize the tasks.
        skip_image: ["*musllinux*", "*manylinux*"]

    env:
      CIBW_ARCHS: ${{ matrix.arch }}
      CIBW_SKIP:  ${{ matrix.skip_image }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VER }}

      # cibuildwheel and PEP-517 don't work on CPython 3.6. This can
      # be removed after cibuildwheel doesn't support CPython 3.6.
      - name: Remove pyproject.toml
        uses: JesseTG/rm@v1.0.3
        with:
          path: pyproject.toml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install cibuildwheel & build wheels
        run: |
          python -m pip install -U cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload ${{ matrix.arch }} wheels
        uses: actions/upload-artifact@v3
        with:
          name: pyzstd-files
          path: wheelhouse/*.whl

  # If the head commit message contains '<more-tests>', run test on
  # armv6/armv7/aarch64/ppc64le/s390x/riscv64 architectures.
  test_on_arches:
    name: Test on ${{ matrix.distro }} ${{ matrix.arch }}
    if: github.event_name == 'push' && contains(github.event.head_commit.message, '<more-tests>')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [armv6, armv7, aarch64, ppc64le, s390x]
        distro: [alpine_latest]
        include:
          - arch: riscv64
            distro: alpine_edge

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: uraimo/run-on-arch-action@v2
        name: Build & run test
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          install: |
            apk update
            apk add python3 python3-dev py3-pip build-base gcc

          run: |
            python3 -c "import platform; print('Machine type:', platform.machine())"
            python3 -m pip install --config-settings="--build-option=--warning-as-error" -v .
            python3 -c "import pyzstd; print('PYZSTD_CONFIG:', pyzstd.PYZSTD_CONFIG)"
            python3 tests/test_zstd.py

  # Upload to PyPI
  upload_pypi:
    name: Publish to PyPI
    needs: [build_wheels, build_in_manylinux2010, build_arch_wheels]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pyzstd-files
          path: dist

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
          verbose: true
          print_hash: true
